Repository saladuit/BuzingaServ, pull requests merged in 2023-09, with the labels that each got.

#11 Config Parser & Logger
  .gitignore
  Makefile
  README.md
  compile_commands.json
  config/default.conf
  include/ConfigParser.hpp
  include/Defines.hpp
  include/HTTPError.hpp
  include/HTTPRequest.hpp
  include/HTTPResponse.hpp
  include/HTTPServer.hpp
  include/Logger.hpp
  include/SocketManager.hpp
  include/ThreadPool.hpp
  include/WebServ.hpp
  makerc/definitions.mk
  src/ConfigParser.cpp
  src/HTTPServer.cpp
  src/Logger.cpp
  src/main.cpp
  tests/request/delete.txt
  tests/request/get.txt
  tests/request/post.txt
  tests/test.sh
  www/index.html
Labels: 💫enhancement

#21 Http server
  .gitignore
  Makefile
  config/default.conf
  include/ConfigParser.hpp
  include/HTTPServer.hpp
  include/Logger.hpp
  include/ThreadPool.hpp
  makerc/definitions.mk
  src/ConfigParser.cpp
  src/HTTPServer.cpp
  src/Logger.cpp
  src/ThreadPool.cpp
  src/main.cpp
  tests/get_request.sh
  tests/test.sh
Labels: 💫enhancement, 🧪test

#24 Ended up not using k6 but cURL in shell script
  .gitignore
  tests/README_tests.md
  tests/sh_script/request/delete.txt
  tests/sh_script/request/get.txt
  tests/sh_script/request/post.txt
  tests/test.sh
Labels: 🧪test

#26 Fixed a lot of const stuff
  include/ConfigParser.hpp
  include/Logger.hpp
  src/ConfigParser.cpp
  src/Logger.cpp
  tests/request/delete.txt
  tests/request/get.txt
  tests/request/post.txt
Labels: 🔧refactor

#27 Get_local.sh
  Makefile
  tests/GET_local.sh
  tests/test.sh
Labels: 💫enhancement

#28 added right path for webserver.log & addes else to if-statement
  .gitignore
  include/Logger.hpp
  src/Logger.cpp
Labels: 🐛bug, 💫enhancement

#29 GET_local.sh usability
  tests/GET_local.sh
Labels: 💫enhancement
